// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2QRZS77Xkt7JxApwy-aLRH3hl49cVPPI',
    appId: '1:776870107682:web:5ff3c36aed03cf39b5487b',
    messagingSenderId: '776870107682',
    projectId: 'dairy-nova',
    authDomain: 'dairy-nova.firebaseapp.com',
    storageBucket: 'dairy-nova.firebasestorage.app',
    measurementId: 'G-1RY6D6S1R9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzbdK8kQxUugvnQTE-a7DcSg4mNPAJJLg',
    appId: '1:776870107682:android:b30c505f841a2581b5487b',
    messagingSenderId: '776870107682',
    projectId: 'dairy-nova',
    storageBucket: 'dairy-nova.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMcSOpHaGLSPtdnWqbjfinzc1yKZmM6is',
    appId: '1:776870107682:ios:2820fb4c75c2e020b5487b',
    messagingSenderId: '776870107682',
    projectId: 'dairy-nova',
    storageBucket: 'dairy-nova.firebasestorage.app',
    iosBundleId: 'com.example.dairyNovaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMcSOpHaGLSPtdnWqbjfinzc1yKZmM6is',
    appId: '1:776870107682:ios:2820fb4c75c2e020b5487b',
    messagingSenderId: '776870107682',
    projectId: 'dairy-nova',
    storageBucket: 'dairy-nova.firebasestorage.app',
    iosBundleId: 'com.example.dairyNovaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2QRZS77Xkt7JxApwy-aLRH3hl49cVPPI',
    appId: '1:776870107682:web:7131197ed38e5395b5487b',
    messagingSenderId: '776870107682',
    projectId: 'dairy-nova',
    authDomain: 'dairy-nova.firebaseapp.com',
    storageBucket: 'dairy-nova.firebasestorage.app',
    measurementId: 'G-JN7G4GTG0S',
  );
}